-- AlterEnum
ALTER TYPE "CommentStatus" ADD VALUE 'PENDING_CONTENT_REVIEW';

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'COMMENT_REPORTED_TO_AUTHOR';
ALTER TYPE "NotificationType" ADD VALUE 'COMMENT_FLAGGED_RESTORED';
ALTER TYPE "NotificationType" ADD VALUE 'COMMENT_FLAGGED_REMOVED';
