/**
 * Read-only diagnostic; run from repo root:
 *   npx tsx --tsconfig tsconfig.json scripts/book-table-diagnostic.ts
 * Writes BOOK_TABLE_DIAGNOSTIC.md at repo root.
 */
import { config } from "dotenv";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@db";
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = process.cwd();
config({ path: resolve(root, ".env") });
config({ path: resolve(root, ".env.local"), override: true });

const connectionString = process.env.DIRECT_URL?.trim() || process.env.DATABASE_URL?.trim();
if (!connectionString) {
  throw new Error("DATABASE_URL is not set");
}
const prisma = new PrismaClient({
  adapter: new PrismaNeon({ connectionString }),
});

const outPath = join(root, "BOOK_TABLE_DIAGNOSTIC.md");

async function main() {
  const total = await prisma.book.count();

  const books = await prisma.book.findMany({
    orderBy: { title: "asc" },
    select: {
      id: true,
      title: true,
      status: true,
      ownerId: true,
      isPublicDomain: true,
    },
  });

  const nullOwnerCount = await prisma.book.count({ where: { ownerId: null } });
  const publishedCount = await prisma.book.count({ where: { status: "published" } });
  const publishedNullOwner = await prisma.book.count({
    where: { status: "published", ownerId: null },
  });

  const rows = books
    .map(
      (b) =>
        `| ${b.id} | ${escapeCell(b.title)} | ${b.status} | ${b.ownerId ?? "null"} | ${b.isPublicDomain} |`,
    )
    .join("\n");

  const md = `# Book table diagnostic (read-only)

Generated: ${new Date().toISOString()}

## 1. Total books

**${total}**

## 2. Each book (id, title, status, ownerId, isPublicDomain)

| id | title | status | ownerId | isPublicDomain |
|----|-------|--------|---------|----------------|
${rows}

## 3. Books with \`ownerId\` null

**${nullOwnerCount}**

## 4. Books with status \`published\`

**${publishedCount}**

## 5. Published books with \`ownerId\` null

**${publishedNullOwner}**  
${publishedNullOwner > 0 ? "Yes — at least one row matches." : "No — none."}

## 6. Delete functions for books (codebase survey)

### API routes

- **\`DELETE /api/admin/books/[id]\`** — \`app/api/admin/books/[id]/route.ts\`  
  \`export async function DELETE\`: requires signed-in user; book must exist; caller must be **admin** OR book \`ownerId\` must equal current user id; then \`prisma.book.delete({ where: { id } })\`.

### Client components (call the above API)

- **\`app/admin/books/[id]/admin-book-detail-client.tsx\`** — \`deleteBook()\` → \`fetch(\`/api/admin/books/\${book.id}\`, { method: "DELETE" })\`.
- **\`app/admin/books/admin-books-client.tsx\`** — \`deleteBook(book)\` → same DELETE URL.
- **\`app/(partner)/partner/books/[id]/partner-book-detail-client.tsx\`** — \`deleteBook()\` → same **admin** DELETE route (\`/api/admin/books/\${book.id}\`), not a partner-specific delete route.

There is **no** \`DELETE\` handler under \`app/api/partner/books/[id]/route.ts\` in the surveyed file (partner updates use \`PATCH\` only). Other deletions in the codebase are **chapters**, **chunks**, or related rows during ingest — not whole-book delete except the admin route above.

## 7. Public \`/books\` catalogue query

**Server file:** \`app/(public)/books/page.tsx\`

**Prisma query:**

\`\`\`ts
const books = await prisma.book.findMany({
  where: { status: "published" },
  orderBy: { title: "asc" },
  select: {
    id: true,
    title: true,
    author: true,
    description: true,
    genre: true,
    coverImageUrl: true,
  },
});
\`\`\`

**Conditions:**

- DB: **only** \`status === "published"\`.  
- No filter on \`ownerId\`, \`isPublicDomain\`, or other fields at query time.

**Client (\`book-catalogue.tsx\`):** After load, the UI filters by **genre** only (including “All genres”). Copy on the page refers to “Public-domain works”; that is **not** enforced by this query unless all published rows happen to be public domain.

---

_Report generated by \`scripts/book-table-diagnostic.ts\` (read-only DB access)._
`;

  writeFileSync(outPath, md, "utf8");
  console.log(`Wrote ${outPath}`);
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
