import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | NovelViz",
  description: "Terms governing your use of NovelViz.",
};

const LAST_UPDATED = "June 25, 2026";
const EFFECTIVE_DATE = "June 25, 2026";

const h2 = "text-lg font-semibold tracking-tight text-text-primary sm:text-xl";
const h3 = "mt-6 text-base font-semibold tracking-tight text-text-primary";
const p = "mt-3 text-sm leading-relaxed text-text-muted sm:text-[15px]";
const ul = "mt-3 list-disc space-y-2 pl-5 text-sm leading-relaxed text-text-muted sm:text-[15px]";
const linkClass =
  "text-accent-text underline-offset-2 hover:text-text-primary hover:underline";
const strong = "font-medium text-text-primary";

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-12 text-text-primary sm:px-6 sm:py-16">
      <h1 className="font-serif text-3xl font-semibold tracking-tight sm:text-4xl">Terms of Service</h1>
      <p className="mt-2 text-sm text-text-secondary">Last updated: {LAST_UPDATED}</p>
      <p className="mt-1 text-sm text-text-secondary">Effective date: {EFFECTIVE_DATE}</p>

      <div className="mt-10 space-y-8">
        <section>
          <h2 className={h2}>1. Agreement to These Terms</h2>
          <p className={p}>
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of novelviz.com and the NovelViz
            application (the &quot;Service&quot;), operated by NovelViz, based in Vancouver, British Columbia, Canada.
            By creating an account or using the Service, you agree to these Terms and to our{" "}
            <Link href="/privacy" className={linkClass}>
              Privacy Policy
            </Link>
            . If you don&apos;t agree, please don&apos;t use the Service.
          </p>
          <p className={p}>
            NovelViz is built and run by a single founder, so &quot;we,&quot; &quot;us,&quot; and &quot;I&quot; may both
            appear in places. Both refer to NovelViz.
          </p>
        </section>

        <section>
          <h2 className={h2}>2. Eligibility</h2>
          <p className={p}>
            You must be 18 years of age or older to use the Service. By using the Service, you represent that you meet
            this requirement. We don&apos;t independently verify age. See our{" "}
            <Link href="/privacy" className={linkClass}>
              Privacy Policy
            </Link>{" "}
            for more on how we handle this.
          </p>
        </section>

        <section>
          <h2 className={h2}>3. Your Account</h2>
          <ul className={ul}>
            <li>
              You need an account to use most of the Service. Account creation and sign-in are handled through our
              authentication provider, Clerk.
            </li>
            <li>You&apos;re responsible for keeping your login credentials secure and for all activity under your account.</li>
            <li>You agree to provide accurate information and to keep it up to date.</li>
            <li>One account per person. You may not share your account or let others use it.</li>
            <li>
              We may suspend or terminate your account for violating these Terms or our{" "}
              <Link href="/acceptable-use" className={linkClass}>
                Acceptable Use Policy
              </Link>
              , or for any reason described in Section 11.
            </li>
          </ul>
        </section>

        <section>
          <h2 className={h2}>4. The Service</h2>
          <p className={p}>
            NovelViz lets you track books you&apos;re reading, ask AI-generated questions about books based only on the
            chapters you&apos;ve reached, and generate AI images related to those books, also limited to chapters
            you&apos;ve reached.
          </p>
          <p className={p}>A few things worth understanding plainly:</p>
          <ul className={ul}>
            <li>
              <span className={strong}>The Service is not a substitute for reading the book.</span> We don&apos;t host or
              display full book text for in-app reading. You add books you own or are reading elsewhere, and track your
              progress yourself.
            </li>
            <li>
              <span className={strong}>Spoiler protection is a best effort, not a guarantee.</span> Our chapter-gating
              system is the core of the product and we take it seriously, but AI responses can occasionally behave
              unexpectedly, and we can&apos;t guarantee that no response will ever reveal something you hadn&apos;t
              reached yet. Use your own judgment, especially near major plot turns.
            </li>
            <li>
              <span className={strong}>AI responses and generated images may be inaccurate, generic, or just wrong.</span>{" "}
              They&apos;re generated by third-party AI models (see Section 9) and are provided for entertainment and
              engagement purposes, not as authoritative information about any book.
            </li>
            <li>
              <span className={strong}>We may change, limit, or discontinue features</span> at our discretion, including
              the specific AI models used to generate responses or images.
            </li>
          </ul>
        </section>

        <section>
          <h2 className={h2}>5. Plans, Credits, and Billing</h2>
          <ul className={ul}>
            <li>
              NovelViz offers Free, Standard, and Premium subscription tiers with different monthly usage allowances,
              plus optional one-time credit packs for additional usage.
            </li>
            <li>
              The Free tier doesn&apos;t require a payment card. Standard is available as a paid plan from the start; you
              can subscribe whenever you&apos;re ready.
            </li>
            <li>
              Once you subscribe to a paid tier: subscription fees are billed in advance on a recurring basis through our
              payment processor, Stripe, which collects your payment details directly. We never see or store your card
              details.
            </li>
            <li>
              <span className={strong}>Purchased credits never expire</span>, except as described in Section 11 (account
              termination and deletion).
            </li>
            <li>
              You can cancel a subscription at any time; cancellation takes effect at the end of your current billing
              period unless stated otherwise.
            </li>
            <li>
              We may change prices or plan features going forward. If you&apos;re an existing subscriber, see our
              commitment below.
            </li>
          </ul>

          <h3 className={h3}>Our commitment to existing subscribers</h3>
          <p className={p}>
            We aim never to remove a feature from a plan you&apos;re already subscribed to, and to pass model or
            capability upgrades through to all tiers rather than holding them back for new, more expensive plans. New
            tiers, when we introduce them, will contain genuinely new capabilities rather than features moved out of
            your existing plan. This is a product commitment, not a substitute for reading the specific terms of your
            plan, which may still change with notice as described in Section 14.
          </p>
        </section>

        <section>
          <h2 className={h2}>6. Your Content</h2>
          <p className={p}>
            &quot;Your Content&quot; means the questions and prompts you submit, any comments you post, and the
            AI-generated answers and images created in response to your activity.
          </p>
          <ul className={ul}>
            <li>
              <span className={strong}>
                The legal status of AI-generated output is unsettled in many jurisdictions, including Canada
              </span>
              , and we can&apos;t promise that what you generate qualifies for copyright protection at all. What we can
              tell you plainly: NovelViz doesn&apos;t claim ownership of your generated content. Beyond the license
              below, which we need to operate the Service, we don&apos;t assert any rights to your questions, prompts,
              generated images, or generated text, and you&apos;re free to keep, use, or share them personally.
            </li>
            <li>
              <span className={strong}>You grant us a license</span> to host, store, process, and display Your Content
              as needed to operate the Service, including showing your public gallery images to other users if you
              choose to make them public, and using de-identified or aggregated content for product improvement.
            </li>
            <li>
              <span className={strong}>You&apos;re responsible for what you submit.</span> Don&apos;t submit content that
              violates our{" "}
              <Link href="/acceptable-use" className={linkClass}>
                Acceptable Use Policy
              </Link>{" "}
              or anyone else&apos;s rights.
            </li>
            <li>
              We may remove content or restrict accounts in response to violations, as described in our Acceptable Use
              Policy and our content moderation process.
            </li>
          </ul>
        </section>

        <section>
          <h2 className={h2}>7. Partner and Author Content</h2>
          <p className={p}>
            If you&apos;re a publisher, author, or other partner who uploads book content to NovelViz:
          </p>
          <ul className={ul}>
            <li>
              You represent that you have the necessary rights to upload, license, and permit NovelViz to process the
              content you submit, including for AI-based Q&amp;A and image generation grounded in that content.
            </li>
            <li>You&apos;re responsible for the accuracy and legality of any content you upload.</li>
            <li>
              We may review, reject, or remove partner-submitted content at our discretion, including content that fails
              review for rights, quality, or policy reasons.
            </li>
            <li>Partner accounts may be subject to additional terms provided separately as the partner program develops.</li>
          </ul>
        </section>

        <section>
          <h2 className={h2}>8. Acceptable Use</h2>
          <p className={p}>
            Your use of the Service is also governed by our{" "}
            <Link href="/acceptable-use" className={linkClass}>
              Acceptable Use Policy
            </Link>
            , which sets out what you can&apos;t do or generate on NovelViz. It&apos;s incorporated into these Terms by
            reference. Violating it may result in content removal, account suspension, or termination, as described
            there.
          </p>
        </section>

        <section>
          <h2 className={h2}>9. Third-Party Services</h2>
          <p className={p}>
            NovelViz relies on third-party providers to operate, including Clerk (authentication), Stripe (billing),
            Anthropic and OpenAI (AI processing), fal.ai (image generation), Cloudinary (image storage), and Vercel and
            Neon (hosting and database). These providers have their own terms and acceptable use policies, and your
            prompts and content may be subject to their content rules in addition to ours, meaning a provider may
            decline to process a request independently of any action we take. We aren&apos;t responsible for the
            availability, accuracy, or behavior of these third-party services, though we choose providers we believe are
            reputable and select business/API terms that limit use of your data for their own model training where
            available.
          </p>
        </section>

        <section>
          <h2 className={h2}>10. Intellectual Property</h2>
          <p className={p}>
            NovelViz and its licensors own all rights in the Service itself, including the software, design, branding,
            and underlying technology, other than book content (which belongs to its respective authors, publishers, or
            is in the public domain) and Your Content as described in Section 6. You may not copy, modify,
            reverse-engineer, or create derivative works of the Service except as the Service&apos;s normal
            functionality allows.
          </p>
        </section>

        <section>
          <h2 className={h2}>11. Suspension and Termination</h2>
          <p className={p}>We may suspend or terminate your account, with or without notice, if:</p>
          <ul className={ul}>
            <li>
              You violate these Terms or our{" "}
              <Link href="/acceptable-use" className={linkClass}>
                Acceptable Use Policy
              </Link>
            </li>
            <li>We&apos;re required to do so by law</li>
            <li>Your use creates risk or legal exposure for NovelViz or other users</li>
            <li>You haven&apos;t used the Service for 2 consecutive years</li>
          </ul>
          <p className={p}>
            <span className={strong}>Suspension</span> is provisional. If your account is suspended pending review or an
            appeal, any unused credits and your subscription status are preserved, and restored along with your access if
            the suspension is lifted.
          </p>
          <p className={p}>
            <span className={strong}>Permanent termination</span> is final. If your account is permanently terminated,
            whether because a violation was upheld on appeal or because it was severe enough to skip suspension entirely,
            any unused credits and remaining subscription time are forfeited, with no refund.
          </p>
          <p className={p}>
            You may stop using the Service or delete your account at any time. Voluntary deletion also forfeits any
            unused credits, with no refund, in the same way permanent termination does, since deleting your account
            removes your data as described in our{" "}
            <Link href="/privacy" className={linkClass}>
              Privacy Policy
            </Link>
            . We&apos;ll show you a clear warning about this before you confirm account deletion.
          </p>
        </section>

        <section>
          <h2 className={h2}>12. Disclaimers</h2>
          <p className={p}>
            The Service is provided &quot;as is&quot; and &quot;as available.&quot; To the fullest extent permitted by
            law, we disclaim all warranties, express or implied, including warranties of merchantability, fitness for a
            particular purpose, and non-infringement. We don&apos;t warrant that the Service will be uninterrupted,
            error-free, or that AI-generated content will be accurate, original, or free of unintended spoilers.
          </p>
        </section>

        <section>
          <h2 className={h2}>13. Limitation of Liability</h2>
          <p className={p}>
            To the fullest extent permitted by law, NovelViz will not be liable for any indirect, incidental,
            consequential, or special damages arising from your use of the Service. Our total liability for any claim
            relating to the Service is limited to the amount you paid us in the 12 months before the claim arose, or CAD
            $50, whichever is greater. Nothing in these Terms limits liability that cannot be limited under applicable
            law.
          </p>
        </section>

        <section>
          <h2 className={h2}>14. Changes to These Terms</h2>
          <p className={p}>
            We may update these Terms from time to time. If we make material changes, we&apos;ll notify you through the
            Service or by email and update the date at the top. Continued use after changes take effect means you accept
            the updated Terms. If you don&apos;t agree, please stop using the Service.
          </p>
        </section>

        <section>
          <h2 className={h2}>15. Governing Law and Disputes</h2>
          <p className={p}>
            These Terms are governed by the laws of the Province of British Columbia and the federal laws of Canada
            applicable therein, without regard to conflict of law principles. Any dispute arising from these Terms or
            the Service will be resolved in the courts of British Columbia, and you and NovelViz both agree to that
            venue.
          </p>
        </section>

        <section>
          <h2 className={h2}>16. General</h2>
          <ul className={ul}>
            <li>If any part of these Terms is found unenforceable, the rest remains in effect.</li>
            <li>
              These Terms, along with the{" "}
              <Link href="/privacy" className={linkClass}>
                Privacy Policy
              </Link>{" "}
              and{" "}
              <Link href="/acceptable-use" className={linkClass}>
                Acceptable Use Policy
              </Link>
              , are the entire agreement between you and NovelViz regarding the Service.
            </li>
            <li>
              You may not assign your rights under these Terms. We may assign ours, including in connection with a
              merger, acquisition, or sale of assets.
            </li>
            <li>Our failure to enforce a provision isn&apos;t a waiver of our right to enforce it later.</li>
          </ul>
        </section>

        <section>
          <h2 className={h2}>17. Contact</h2>
          <p className={p}>
            Questions about these Terms: reach out via our{" "}
            <Link href="/contact" className={linkClass}>
              contact page
            </Link>{" "}
            or email{" "}
            <Link href="mailto:hello@novelviz.com" className={linkClass}>
              hello@novelviz.com
            </Link>
            .
          </p>
          <p className={p}>
            NovelViz
            <br />
            Vancouver, British Columbia, Canada
          </p>
        </section>
      </div>
    </article>
  );
}
